[workspace]
resolver = "2"

members = [
    "jaguars",
    "lbf"
]

[profile.release]
opt-level = 3
#lto = "fat"
#codegen-units = 1
#panic = "abort"

[profile.test]
opt-level = 2
debug = true
debug-assertions = false

[profile.dev]
debug = true

[profile.bench]
opt-level = 3
panic = "abort"