[package]
name = "lbf"
version = "0.1.0"
edition = "2021"

[dependencies]
jaguars = { path = "../jaguars" }
rand = { version = "0.8.5", features = [ "small_rng" ] }
rand_distr = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = { version = "1.19.0", features = [] }
fern = "0.6.2"
log = "0.4.20"
humantime = "2.1.0"
itertools = "0.12.0"
svg = "0.14.0"
ordered-float = "4.2.0"
clap = { version = "4.4.18", features = ["derive"] }