name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build targets
        run: |
          cd lbf
          cargo build --all-targets --verbose
      - name: Build docs
        run: |
          cd lbf
          cargo doc

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting jagua-rs
        run: |
          cd jagua-rs
          cargo fmt --all -- --check
      - name: Check formatting lbf
        run: |
          cd lbf
          cargo fmt --all -- --check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd lbf
          cargo test --verbose

  example_in_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Runs the example in the lbf README
        run: |
          cd lbf
          cargo run --release -- -i ../assets/swim.json -c ../assets/config_lbf.json -s ../solutions
