name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd lbf
        cargo build --all-targets --verbose
    - name: Tests
      run: |
        cd lbf
        cargo test -- --nocapture
    - name: Docs
      run : |
        cd lbf
        cargo doc
