name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build targets
        run: |
          cd lbf
          cargo build --all-targets --verbose
      - name: Build docs
        run: |
          cd lbf
          cargo doc
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd lbf
          cargo test --verbose

  run_readme_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run README example
        run: |
          cd lbf
          cargo run --release -- -i ../assets/swim.json -c ../assets/config_lbf.json -s ../solutions
