name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build targets
        run: |
          cd lbf
          cargo build --all-targets --verbose
      - name: build docs
        run: |
          cd lbf
          cargo doc
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          cd lbf
          cargo test --verbose
